"use client";
import { useEffect,useRef } from "react";
import * as THREE from "three";
import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader.js";
import {VRMLoaderPlugin,VRMUtils} from "@pixiv/three-vrm";

type Props={active:boolean;onNearby:(room:string|null)=>void;onMap:()=>void};
const doors=[{id:"gallery",p:new THREE.Vector3(0,0,-8),c:0xc8a66d,r:0},{id:"kitchen",p:new THREE.Vector3(-8,0,0),c:0x8d2940,r:Math.PI/2},{id:"arcade",p:new THREE.Vector3(8,0,0),c:0x6b416f,r:Math.PI/2},{id:"shop",p:new THREE.Vector3(-3.2,0,8),c:0xc8a66d,r:0},{id:"ai-studio",p:new THREE.Vector3(5.2,0,8),c:0x49c7c2,r:0}];
export default function RestaurantGame({active,onNearby,onMap}:Props){const mount=useRef<HTMLDivElement>(null);const activeRef=useRef(active);activeRef.current=active;
useEffect(()=>{if(!mount.current)return;const host=mount.current,scene=new THREE.Scene();scene.background=new THREE.Color(0x120d0f);scene.fog=new THREE.FogExp2(0x120d0f,.022);const camera=new THREE.PerspectiveCamera(55,1,.1,100);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.shadowMap.enabled=true;host.appendChild(renderer.domElement);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(24,24),new THREE.MeshStandardMaterial({color:0x2a2022,roughness:.32,metalness:.25}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);scene.add(new THREE.HemisphereLight(0xffe5c2,0x3b101a,2.8));scene.add(new THREE.AmbientLight(0xffd6ad,.65));const chandelier=new THREE.PointLight(0xffd49a,125,24);chandelier.position.set(0,6,0);chandelier.castShadow=true;scene.add(chandelier);
const wallMat=new THREE.MeshStandardMaterial({color:0x2b171c,roughness:.48});for(const [x,z,sx,sz] of [[0,-10,20,.45],[0,10,20,.45],[-10,0,.45,20],[10,0,.45,20]] as number[][]){const w=new THREE.Mesh(new THREE.BoxGeometry(sx,1.35,sz),wallMat);w.position.set(x,.675,z);scene.add(w)}
const brass=new THREE.MeshStandardMaterial({color:0xc8a66d,metalness:.8,roughness:.23}),velvet=new THREE.MeshStandardMaterial({color:0x511625,roughness:.82}),linen=new THREE.MeshStandardMaterial({color:0xe8dcc6,roughness:.65}),glass=new THREE.MeshPhysicalMaterial({color:0xffead5,transparent:true,opacity:.34,roughness:.08,transmission:.65});const tablePositions=[[-6.6,-5.8],[-3.4,-6.9],[2.2,-6.1],[6.4,-5.3],[-6.8,-2.1],[-2.7,-2.9],[3.8,-2.2],[6.7,-.7],[-5.7,2.2],[-2.3,1.2],[3.3,2.1],[6.1,3.8]];for(const [x,z] of tablePositions){const table=new THREE.Mesh(new THREE.CylinderGeometry(.78,.82,.08,32),new THREE.MeshStandardMaterial({color:0x241619,roughness:.25}));table.position.set(x,.75,z);scene.add(table);const stem=new THREE.Mesh(new THREE.CylinderGeometry(.06,.06,.7,12),brass);stem.position.set(x,.38,z);scene.add(stem);const candle=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.32,10),linen);candle.position.set(x,1,z);scene.add(candle);const flame=new THREE.PointLight(0xffb05a,1.8,2.2);flame.position.set(x,1.27,z);scene.add(flame);for(let i=0;i<3;i++){const a=i/3*Math.PI*2+(x+z)*.11,dx=Math.cos(a),dz=Math.sin(a);const chair=new THREE.Group(),seat=new THREE.Mesh(new THREE.BoxGeometry(.55,.12,.55),velvet),back=new THREE.Mesh(new THREE.BoxGeometry(.58,.72,.1),velvet);seat.position.y=.42;back.position.set(0,.76,.25);chair.add(seat,back);chair.position.set(x+dx*1.22,0,z+dz*1.22);chair.rotation.y=-a+Math.PI/2;scene.add(chair);const plate=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,.018,24),linen);plate.position.set(x+dx*.46,.81,z+dz*.46);scene.add(plate);const goblet=new THREE.Mesh(new THREE.CylinderGeometry(.055,.035,.22,12),glass);goblet.position.set(x+dx*.33-dz*.16,.94,z+dz*.33+dx*.16);scene.add(goblet)}}
const rug=new THREE.Mesh(new THREE.CircleGeometry(4.25,48),new THREE.MeshStandardMaterial({color:0x42131e,roughness:.95}));rug.rotation.x=-Math.PI/2;rug.position.y=.006;scene.add(rug);for(const [x,z] of [[-8.6,-7.8],[8.6,-7.8],[-8.6,7.5],[8.6,7.5]]){const pot=new THREE.Mesh(new THREE.CylinderGeometry(.34,.46,.65,16),brass);pot.position.set(x,.33,z);scene.add(pot);for(let i=0;i<5;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.32,10,8),new THREE.MeshStandardMaterial({color:0x263b2c,roughness:.9}));leaf.scale.set(.45,1.4,.35);leaf.position.set(x+Math.sin(i)*.25,1+i*.08,z+Math.cos(i)*.25);leaf.rotation.z=(i-2)*.22;scene.add(leaf)}}
doors.forEach(d=>{const frame=new THREE.Group();const sideGeo=new THREE.BoxGeometry(.14,3,.25);for(const x of [-1.15,1.15]){const s=new THREE.Mesh(sideGeo,brass);s.position.set(x,1.5,0);frame.add(s)}const top=new THREE.Mesh(new THREE.BoxGeometry(2.44,.14,.25),brass);top.position.y=3;frame.add(top);const glow=new THREE.Mesh(new THREE.PlaneGeometry(2.2,2.8),new THREE.MeshBasicMaterial({color:d.c,transparent:true,opacity:.26,side:THREE.DoubleSide}));glow.position.y=1.5;frame.add(glow);frame.position.copy(d.p);frame.rotation.y=d.r;scene.add(frame);const fill=new THREE.PointLight(d.c,22,7);fill.position.set(d.p.x,2.2,d.p.z);scene.add(fill)});
const station=new THREE.Mesh(new THREE.BoxGeometry(2.8,1.15,.8),new THREE.MeshStandardMaterial({color:0x241619,metalness:.2,roughness:.3}));station.position.set(0,.58,2.7);scene.add(station);const mapLight=new THREE.PointLight(0xc8a66d,18,5);mapLight.position.set(0,1.8,2.7);scene.add(mapLight);
let avatar:THREE.Object3D|null=null;let vrmRig:any=null;const loader=new GLTFLoader();loader.register(p=>new VRMLoaderPlugin(p));loader.load("/void_9628.vrm",g=>{const vrm=g.userData.vrm;vrmRig=vrm;VRMUtils.removeUnnecessaryVertices(g.scene);VRMUtils.rotateVRM0(vrm);avatar=vrm.scene;const box=new THREE.Box3().setFromObject(avatar);const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());avatar.position.sub(center);avatar.position.y+=size.y*.5;avatar.scale.setScalar(1.75/size.y);scene.add(avatar)});
const player=new THREE.Vector3(0,0,5.4),keys=new Set<string>();const down=(e:KeyboardEvent)=>keys.add(e.key.toLowerCase()),up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());window.addEventListener("keydown",down);window.addEventListener("keyup",up);const touchStart=(e:Event)=>{e.preventDefault();const k=(e.currentTarget as HTMLElement).dataset.key;if(k)keys.add(k.toLowerCase())},touchEnd=()=>keys.clear();document.querySelectorAll("[data-key]").forEach(b=>{b.addEventListener("pointerdown",touchStart);b.addEventListener("pointerup",touchEnd);b.addEventListener("pointercancel",touchEnd);b.addEventListener("pointerleave",touchEnd)});
let orbit=0,distance=6.8,dragging=false,lastPointerX=0;const pointerDown=(e:PointerEvent)=>{dragging=true;lastPointerX=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)};const pointerMove=(e:PointerEvent)=>{if(!dragging)return;orbit-=(e.clientX-lastPointerX)*.008;lastPointerX=e.clientX};const pointerUp=()=>{dragging=false};const wheel=(e:WheelEvent)=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*.006,4.2,9)};renderer.domElement.addEventListener("pointerdown",pointerDown);renderer.domElement.addEventListener("pointermove",pointerMove);renderer.domElement.addEventListener("pointerup",pointerUp);renderer.domElement.addEventListener("wheel",wheel,{passive:false});
const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()};resize();const ro=new ResizeObserver(resize);ro.observe(host);const clock=new THREE.Clock();let raf=0,lastNear:string|null=null;
const loop=()=>{raf=requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04);
let moving=false;if(activeRef.current){const v=new THREE.Vector3((keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0),0,(keys.has("s")||keys.has("arrowdown")?1:0)-(keys.has("w")||keys.has("arrowup")?1:0));moving=v.length()>0;if(moving){v.normalize();player.addScaledVector(v,dt*3);player.x=THREE.MathUtils.clamp(player.x,-8.4,8.4);player.z=THREE.MathUtils.clamp(player.z,-8.4,8.4);if(avatar)avatar.rotation.y=Math.atan2(v.x,v.z)+Math.PI}}
const t=performance.now()*.001;if(avatar){avatar.position.x=player.x;avatar.position.z=player.z;avatar.position.y=moving?Math.abs(Math.sin(t*8))*.03:Math.sin(t*1.7)*.008}
if(vrmRig){const bone=(name:string)=>vrmRig.humanoid?.getNormalizedBoneNode(name);const lArm=bone("leftUpperArm"),rArm=bone("rightUpperArm"),lFore=bone("leftLowerArm"),rFore=bone("rightLowerArm"),lLeg=bone("leftUpperLeg"),rLeg=bone("rightUpperLeg"),lShin=bone("leftLowerLeg"),rShin=bone("rightLowerLeg"),chest=bone("chest"),head=bone("head");const smooth=.18;if(moving){const stride=Math.sin(t*8)*.62,follow=Math.max(0,-Math.sin(t*8))*.55;lArm&&(lArm.rotation.x=THREE.MathUtils.lerp(lArm.rotation.x,-stride*.7,smooth),lArm.rotation.z=THREE.MathUtils.lerp(lArm.rotation.z,1.05,smooth));rArm&&(rArm.rotation.x=THREE.MathUtils.lerp(rArm.rotation.x,stride*.7,smooth),rArm.rotation.z=THREE.MathUtils.lerp(rArm.rotation.z,-1.05,smooth));lLeg&&(lLeg.rotation.x=THREE.MathUtils.lerp(lLeg.rotation.x,stride,smooth));rLeg&&(rLeg.rotation.x=THREE.MathUtils.lerp(rLeg.rotation.x,-stride,smooth));lShin&&(lShin.rotation.x=THREE.MathUtils.lerp(lShin.rotation.x,follow,smooth));rShin&&(rShin.rotation.x=THREE.MathUtils.lerp(rShin.rotation.x,Math.max(0,Math.sin(t*8))*.55,smooth));chest&&(chest.rotation.y=Math.sin(t*8)*.06)}else{lArm&&(lArm.rotation.x=THREE.MathUtils.lerp(lArm.rotation.x,.08,smooth),lArm.rotation.z=THREE.MathUtils.lerp(lArm.rotation.z,1.12,smooth));rArm&&(rArm.rotation.x=THREE.MathUtils.lerp(rArm.rotation.x,-.18,smooth),rArm.rotation.z=THREE.MathUtils.lerp(rArm.rotation.z,-1.02,smooth));lFore&&(lFore.rotation.y=THREE.MathUtils.lerp(lFore.rotation.y,-.12,smooth));rFore&&(rFore.rotation.y=THREE.MathUtils.lerp(rFore.rotation.y,.28,smooth));lLeg&&(lLeg.rotation.x=THREE.MathUtils.lerp(lLeg.rotation.x,0,smooth));rLeg&&(rLeg.rotation.x=THREE.MathUtils.lerp(rLeg.rotation.x,0,smooth));lShin&&(lShin.rotation.x=THREE.MathUtils.lerp(lShin.rotation.x,0,smooth));rShin&&(rShin.rotation.x=THREE.MathUtils.lerp(rShin.rotation.x,0,smooth));chest&&(chest.rotation.y=Math.sin(t*.8)*.025);head&&(head.rotation.y=Math.sin(t*.55)*.12,head.rotation.x=Math.sin(t*.7)*.025)}vrmRig.update(dt)}
const desired=new THREE.Vector3(player.x+Math.sin(orbit)*distance,4.5,player.z+Math.cos(orbit)*distance);camera.position.lerp(desired,.09);camera.lookAt(player.x,1,player.z);let near:string|null=null;for(const d of doors)if(player.distanceTo(d.p)<2.4)near=d.id;if(player.distanceTo(new THREE.Vector3(0,0,2.7))<1.7&&keys.has("e"))onMap();if(near!==lastNear){lastNear=near;onNearby(near)}renderer.render(scene,camera)};
loop();return()=>{cancelAnimationFrame(raf);ro.disconnect();window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);renderer.domElement.removeEventListener("pointerdown",pointerDown);renderer.domElement.removeEventListener("pointermove",pointerMove);renderer.domElement.removeEventListener("pointerup",pointerUp);renderer.domElement.removeEventListener("wheel",wheel);renderer.dispose();host.removeChild(renderer.domElement)}} ,[]);return <div className="game-canvas" ref={mount}/>}
