"use client";
import { useEffect,useRef } from "react";
import * as THREE from "three";
import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader.js";
import {addDiningFurniture} from "./DiningFurniture";
import {FBXLoader} from "three/examples/jsm/loaders/FBXLoader.js";
import {VRMLoaderPlugin,VRMUtils} from "@pixiv/three-vrm";

type Props={active:boolean;onNearby:(room:string|null)=>void;onMap:()=>void};
const doors=[{id:"gallery",label:"GALLERY",p:new THREE.Vector3(0,0,-10),c:0xc8a66d,r:0},{id:"kitchen",label:"KITCHEN",p:new THREE.Vector3(-10,0,0),c:0x8d2940,r:Math.PI/2},{id:"arcade",label:"ARCADE",p:new THREE.Vector3(10,0,0),c:0x6b416f,r:Math.PI/2},{id:"shop",label:"GIFT SHOP",p:new THREE.Vector3(-3.2,0,10),c:0xc8a66d,r:0},{id:"ai-studio",label:"AI STUDIO",p:new THREE.Vector3(5.2,0,10),c:0x49c7c2,r:0}];
const mixamoBones:Record<string,string>={mixamorigHips:"hips",mixamorigSpine:"spine",mixamorigSpine1:"chest",mixamorigSpine2:"upperChest",mixamorigNeck:"neck",mixamorigHead:"head",mixamorigLeftShoulder:"leftShoulder",mixamorigLeftArm:"leftUpperArm",mixamorigLeftForeArm:"leftLowerArm",mixamorigLeftHand:"leftHand",mixamorigLeftUpLeg:"leftUpperLeg",mixamorigLeftLeg:"leftLowerLeg",mixamorigLeftFoot:"leftFoot",mixamorigLeftToeBase:"leftToes",mixamorigRightShoulder:"rightShoulder",mixamorigRightArm:"rightUpperArm",mixamorigRightForeArm:"rightLowerArm",mixamorigRightHand:"rightHand",mixamorigRightUpLeg:"rightUpperLeg",mixamorigRightLeg:"rightLowerLeg",mixamorigRightFoot:"rightFoot",mixamorigRightToeBase:"rightToes"};
const retargetMixamo=(source:any,clip:THREE.AnimationClip,vrm:any)=>{source.updateMatrixWorld(true);const flip=vrm.meta?.metaVersion==="0";const tracks=clip.tracks.flatMap(track=>{if(!track.name.endsWith(".quaternion"))return[];const sourceName=track.name.slice(0,-".quaternion".length),sourceBone=source.getObjectByName(sourceName),target=vrm.humanoid?.getNormalizedBoneNode(mixamoBones[sourceName]);if(!sourceBone||!target)return[];const inverse=sourceBone.getWorldQuaternion(new THREE.Quaternion()).invert(),parent=sourceBone.parent?sourceBone.parent.getWorldQuaternion(new THREE.Quaternion()):new THREE.Quaternion(),values=Float32Array.from(track.values),rotation=new THREE.Quaternion();for(let i=0;i<values.length;i+=4){rotation.fromArray(values,i).premultiply(parent).multiply(inverse);if(flip){rotation.x*=-1;rotation.z*=-1}rotation.toArray(values,i)}return[new THREE.QuaternionKeyframeTrack(`${target.name}.quaternion`,Float32Array.from(track.times),values)]});return new THREE.AnimationClip("RestaurantWalk",clip.duration,tracks)};
const createIdleClip=(vrm:any)=>{const times=Float32Array.from([0,1.35,2.7,4.05]);return new THREE.AnimationClip("RestaurantIdle",4.05,[...["chest","head","leftUpperArm","rightUpperArm"].flatMap((name,index)=>{const bone=vrm.humanoid?.getRawBoneNode(name);if(!bone)return[];const rest=bone.quaternion.clone(),sway=index===0?.025:index===1?.075:.035,pose=(y:number,z=0)=>rest.clone().multiply(new THREE.Quaternion().setFromEuler(new THREE.Euler(0,y,z))),values=Float32Array.from([rest.toArray(),pose(sway,index===2?-.025:index===3?.025:0).toArray(),pose(-sway,index===2?.02:index===3?-.02:0).toArray(),rest.toArray()].flat());return[new THREE.QuaternionKeyframeTrack(`${bone.name}.quaternion`,times,values)]})]);};
const restaurantWalkUrl="/animations/restaurant-casual-walk.fbx";
THREE.DefaultLoadingManager.setURLModifier(url=>url.endsWith("/animations/walking-from-standing.fbx")?restaurantWalkUrl:url);
export default function RestaurantGame({active,onNearby,onMap}:Props){const mount=useRef<HTMLDivElement>(null);const activeRef=useRef(active);activeRef.current=active;
useEffect(()=>{if(!mount.current)return;const host=mount.current,scene=new THREE.Scene();scene.background=new THREE.Color(0x120d0f);scene.fog=new THREE.FogExp2(0x120d0f,.022);const camera=new THREE.PerspectiveCamera(55,1,.1,100);camera.position.set(0,2.5,8.9);camera.lookAt(0,1.18,4.15);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(renderer.domElement);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(24,24),new THREE.MeshStandardMaterial({color:0x2a2022,roughness:.62,metalness:.03}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);scene.add(new THREE.HemisphereLight(0xffe5c2,0x3b3032,.85));scene.add(new THREE.AmbientLight(0xffead9,.18));const disposeDining=addDiningFurniture(scene,renderer);
const wallMat=new THREE.MeshStandardMaterial({color:0x2b171c,roughness:.48,metalness:.08}),ceilingMat=new THREE.MeshStandardMaterial({color:0x1a1015,roughness:.7,metalness:.18}),crown=new THREE.MeshStandardMaterial({color:0xc8a66d,metalness:.85,roughness:.2});const addWall=(from:number,to:number,fixed:number,horizontal:boolean)=>{const length=to-from;if(length<=0)return;const w=new THREE.Mesh(new THREE.BoxGeometry(horizontal ? length : .45,7.7,horizontal ? .45 : length),wallMat);w.position.set(horizontal?(from+to)/2:fixed,3.85,horizontal?fixed:(from+to)/2);w.castShadow=true;w.receiveShadow=true;scene.add(w);for(const y of [.44,2.45,7.43]){const trim=new THREE.Mesh(new THREE.BoxGeometry(horizontal ? length : .12,y===7.43 ? .12 : .09,horizontal ? .12 : length),crown);trim.position.set(horizontal?(from+to)/2:fixed,y,horizontal?fixed:(from+to)/2);scene.add(trim)}};
addWall(-10,-1.3,-10,true);addWall(1.3,10,-10,true);addWall(-10,-4.5,10,true);addWall(-1.9,3.9,10,true);addWall(6.5,10,10,true);addWall(-10,-1.3,-10,false);addWall(1.3,10,-10,false);addWall(-10,-1.3,10,false);addWall(1.3,10,10,false);const ceiling=new THREE.Mesh(new THREE.BoxGeometry(20,0.22,20),ceilingMat);ceiling.position.y=7.7;scene.add(ceiling);
for(const [x,z,r] of [[-5.6,-7.73,0],[4.6,-7.73,0],[-7.73,-4.7,Math.PI/2],[7.73,4.6,Math.PI/2]] as number[][]){const sconce=new THREE.Group();const plate=new THREE.Mesh(new THREE.CylinderGeometry(.19,.19,.06,16),crown);plate.rotation.x=Math.PI/2;plate.position.set(x,2.9,z);sconce.add(plate);const lamp=new THREE.Mesh(new THREE.SphereGeometry(.16,16,12),new THREE.MeshBasicMaterial({color:0xffd8a0}));lamp.position.set(x,2.9,z);sconce.add(lamp);const glow=new THREE.PointLight(0xffc878,8,3.2);glow.position.set(x+(r ? -.16 : 0),2.9,z+(r ? 0 : .16));sconce.add(glow);scene.add(sconce)}
const chandelier=new THREE.Group();const chain=new THREE.Mesh(new THREE.CylinderGeometry(.045,.045,1.15,12),crown);chain.position.y=7.05;chandelier.add(chain);for(const [radius,y] of [[1.15,6.4],[.7,5.92]] as number[][]){const ring=new THREE.Mesh(new THREE.TorusGeometry(radius,.045,10,40),crown);ring.rotation.x=Math.PI/2;ring.position.y=y;chandelier.add(ring);for(let i=0;i<14;i++){const a=i/14*Math.PI*2;const crystal=new THREE.Mesh(new THREE.OctahedronGeometry(.09,0),new THREE.MeshPhysicalMaterial({color:0xfff5df,metalness:.05,roughness:.05,transmission:.45,transparent:true,opacity:.9}));crystal.position.set(Math.cos(a)*radius,y-.23-(i%2)*.12,Math.sin(a)*radius);chandelier.add(crystal)}}const chandelierLight=new THREE.PointLight(0xffd49a,155,25);chandelierLight.position.y=6.15;chandelierLight.castShadow=false;chandelier.add(chandelierLight);scene.add(chandelier);
const brass=new THREE.MeshStandardMaterial({color:0xb29a62,metalness:.82,roughness:.32});
const rug=new THREE.Mesh(new THREE.CircleGeometry(4.25,48),new THREE.MeshStandardMaterial({color:0x42131e,roughness:.95}));rug.rotation.x=-Math.PI/2;rug.position.y=.006;scene.add(rug);for(const [x,z] of [[-8.6,-7.8],[8.6,-7.8],[-8.6,7.5],[8.6,7.5]]){const pot=new THREE.Mesh(new THREE.CylinderGeometry(.34,.46,.65,16),brass);pot.position.set(x,.33,z);scene.add(pot);for(let i=0;i<5;i++){const leaf=new THREE.Mesh(new THREE.SphereGeometry(.32,10,8),new THREE.MeshStandardMaterial({color:0x263b2c,roughness:.9}));leaf.scale.set(.45,1.4,.35);leaf.position.set(x+Math.sin(i)*.25,1+i*.08,z+Math.cos(i)*.25);leaf.rotation.z=(i-2)*.22;scene.add(leaf)}}
const neonLabel=(label:string,color:number)=>{const canvas=document.createElement("canvas");canvas.width=768;canvas.height=160;const ctx=canvas.getContext("2d")!;const css=`#${color.toString(16).padStart(6,"0")}`;ctx.textAlign="center";ctx.textBaseline="middle";ctx.font="700 62px Arial";ctx.lineWidth=5;ctx.strokeStyle=css;ctx.shadowColor=css;ctx.shadowBlur=26;ctx.strokeText(label,384,82);ctx.fillStyle="#fff5e8";ctx.shadowBlur=12;ctx.fillText(label,384,82);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;return texture};
doors.forEach(d=>{const frame=new THREE.Group();const sideGeo=new THREE.BoxGeometry(.14,3,.25);for(const x of [-1.15,1.15]){const s=new THREE.Mesh(sideGeo,brass);s.position.set(x,1.5,0);frame.add(s)}const top=new THREE.Mesh(new THREE.BoxGeometry(2.44,.14,.25),brass);top.position.y=3;frame.add(top);const glow=new THREE.Mesh(new THREE.PlaneGeometry(2.2,2.8),new THREE.MeshBasicMaterial({color:d.c,transparent:true,opacity:.26,side:THREE.DoubleSide}));glow.position.y=1.5;frame.add(glow);const signSide=d.id==="gallery"||d.id==="kitchen"?1:-1;const signBack=new THREE.Mesh(new THREE.BoxGeometry(2.12,.48,.06),new THREE.MeshStandardMaterial({color:0x160d12,metalness:.45,roughness:.35}));signBack.position.set(0,3.56,signSide*.05);frame.add(signBack);const sign=new THREE.Mesh(new THREE.PlaneGeometry(1.98,.4),new THREE.MeshBasicMaterial({map:neonLabel(d.label,d.c),transparent:true,depthWrite:false,side:THREE.DoubleSide}));sign.position.set(0,3.56,signSide*.085);sign.rotation.y=signSide<0?Math.PI:0;frame.add(sign);frame.position.copy(d.p);frame.rotation.y=d.r;scene.add(frame);const fill=new THREE.PointLight(d.c,22,7);fill.position.set(d.p.x,2.2,d.p.z);scene.add(fill);const signGlow=new THREE.PointLight(d.c,7,3.5);signGlow.position.set(d.p.x,3.55,d.p.z);scene.add(signGlow)});
let avatar:THREE.Object3D|null=null;let vrmRig:any=null;let walkMixer:THREE.AnimationMixer|null=null,walkAction:THREE.AnimationAction|null=null,idleMixer:THREE.AnimationMixer|null=null,idleAction:THREE.AnimationAction|null=null;const loader=new GLTFLoader();loader.register(p=>new VRMLoaderPlugin(p));loader.load("/void_9628.vrm",g=>{const vrm=g.userData.vrm;vrmRig=vrm;VRMUtils.removeUnnecessaryVertices(g.scene);VRMUtils.rotateVRM0(vrm);avatar=vrm.scene;const box=new THREE.Box3().setFromObject(avatar);const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());avatar.position.sub(center);avatar.position.y+=size.y*.5;avatar.scale.setScalar(1.75/size.y);avatar.traverse(object=>{if(object instanceof THREE.Mesh){object.castShadow=true;object.receiveShadow=true;}});scene.add(avatar);const idleClip=createIdleClip(vrm);if(idleClip.tracks.length){idleMixer=new THREE.AnimationMixer(avatar);idleAction=idleMixer.clipAction(idleClip);idleAction.setLoop(THREE.LoopRepeat,Infinity);idleAction.play()}new FBXLoader().load("/animations/walking-from-standing.fbx",source=>{const sourceClip=source.animations[0];if(sourceClip&&avatar){const clip=retargetMixamo(source,sourceClip,vrm);if(clip.tracks.length){walkMixer=new THREE.AnimationMixer(avatar);walkAction=walkMixer.clipAction(clip);walkAction.setLoop(THREE.LoopRepeat,Infinity);walkAction.play();walkAction.paused=true}}})});
const player=new THREE.Vector3(0,0,4.4),keys=new Set<string>();let viewMode=0;const down=(e:KeyboardEvent)=>{if(!activeRef.current)return;if(e.code==="KeyV"&&!e.repeat){viewMode=(viewMode+1)%3;return}keys.add(e.key.toLowerCase())},up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());window.addEventListener("keydown",down);window.addEventListener("keyup",up);const touchStart=(e:Event)=>{e.preventDefault();if(!activeRef.current)return;const k=(e.currentTarget as HTMLElement).dataset.key;if(k)keys.add(k.toLowerCase())},touchEnd=()=>keys.clear();document.querySelectorAll("[data-key]").forEach(b=>{b.addEventListener("pointerdown",touchStart);b.addEventListener("pointerup",touchEnd);b.addEventListener("pointercancel",touchEnd);b.addEventListener("pointerleave",touchEnd)});
let orbit=0,distance=5.2,dragging=false,lastPointerX=0;const pointerDown=(e:PointerEvent)=>{dragging=true;lastPointerX=e.clientX;renderer.domElement.setPointerCapture(e.pointerId)};const pointerMove=(e:PointerEvent)=>{if(!dragging)return;orbit-=(e.clientX-lastPointerX)*.008;lastPointerX=e.clientX};const pointerUp=()=>{dragging=false};const wheel=(e:WheelEvent)=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*.006,4.2,9)};renderer.domElement.addEventListener("pointerdown",pointerDown);renderer.domElement.addEventListener("pointermove",pointerMove);renderer.domElement.addEventListener("pointerup",pointerUp);renderer.domElement.addEventListener("wheel",wheel,{passive:false});
const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()};resize();const ro=new ResizeObserver(resize);ro.observe(host);const clock=new THREE.Clock();let raf=0,lastNear:string|null=null;
const loop=()=>{raf=requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04);
let moving=false;if(activeRef.current){const v=new THREE.Vector3((keys.has("d")||keys.has("arrowright")?1:0)-(keys.has("a")||keys.has("arrowleft")?1:0),0,(keys.has("s")||keys.has("arrowdown")?1:0)-(keys.has("w")||keys.has("arrowup")?1:0));moving=v.length()>0;if(moving){v.normalize();player.addScaledVector(v,dt*3);player.x=THREE.MathUtils.clamp(player.x,-8.4,8.4);player.z=THREE.MathUtils.clamp(player.z,-8.4,8.4);if(avatar)avatar.rotation.y=Math.atan2(v.x,v.z)+Math.PI}}
const t=performance.now()*.001;if(avatar){avatar.rotation.x=-.025;avatar.position.x=player.x;avatar.position.z=player.z;avatar.position.y=moving?Math.abs(Math.sin(t*8))*.03:Math.sin(t*1.7)*.008}
if(walkAction){walkAction.paused=!moving;if(moving)walkMixer?.update(dt)}if(vrmRig){const bone=(name:string)=>vrmRig.humanoid?.getNormalizedBoneNode(name);const lArm=bone("leftUpperArm"),rArm=bone("rightUpperArm"),lFore=bone("leftLowerArm"),rFore=bone("rightLowerArm"),lLeg=bone("leftUpperLeg"),rLeg=bone("rightUpperLeg"),lShin=bone("leftLowerLeg"),rShin=bone("rightLowerLeg"),chest=bone("chest"),head=bone("head");const smooth=.18;if(moving){if(!walkAction){const stride=Math.sin(t*8)*.62,follow=Math.max(0,-Math.sin(t*8))*.55;lArm&&(lArm.rotation.x=THREE.MathUtils.lerp(lArm.rotation.x,-stride*.7,smooth),lArm.rotation.z=THREE.MathUtils.lerp(lArm.rotation.z,1.05,smooth));rArm&&(rArm.rotation.x=THREE.MathUtils.lerp(rArm.rotation.x,stride*.7,smooth),rArm.rotation.z=THREE.MathUtils.lerp(rArm.rotation.z,-1.05,smooth));lLeg&&(lLeg.rotation.x=THREE.MathUtils.lerp(lLeg.rotation.x,stride,smooth));rLeg&&(rLeg.rotation.x=THREE.MathUtils.lerp(rLeg.rotation.x,-stride,smooth));lShin&&(lShin.rotation.x=THREE.MathUtils.lerp(lShin.rotation.x,follow,smooth));rShin&&(rShin.rotation.x=THREE.MathUtils.lerp(rShin.rotation.x,Math.max(0,Math.sin(t*8))*.55,smooth));chest&&(chest.rotation.y=Math.sin(t*8)*.06)}}else{const breathe=Math.sin(t*1.1);lArm&&(lArm.rotation.x=THREE.MathUtils.lerp(lArm.rotation.x,.08+breathe*.02,smooth),lArm.rotation.z=THREE.MathUtils.lerp(lArm.rotation.z,1.12,smooth));rArm&&(rArm.rotation.x=THREE.MathUtils.lerp(rArm.rotation.x,-.18-breathe*.02,smooth),rArm.rotation.z=THREE.MathUtils.lerp(rArm.rotation.z,-1.02,smooth));lFore&&(lFore.rotation.y=THREE.MathUtils.lerp(lFore.rotation.y,-.12,smooth));rFore&&(rFore.rotation.y=THREE.MathUtils.lerp(rFore.rotation.y,.28,smooth));lLeg&&(lLeg.rotation.x=THREE.MathUtils.lerp(lLeg.rotation.x,0,smooth));rLeg&&(rLeg.rotation.x=THREE.MathUtils.lerp(rLeg.rotation.x,0,smooth));lShin&&(lShin.rotation.x=THREE.MathUtils.lerp(lShin.rotation.x,0,smooth));rShin&&(rShin.rotation.x=THREE.MathUtils.lerp(rShin.rotation.x,0,smooth));chest&&(chest.rotation.y=Math.sin(t*.8)*.025, chest.rotation.x=breathe*.018);head&&(head.rotation.y=Math.sin(t*.55)*.12,head.rotation.x=Math.sin(t*.7)*.025)}vrmRig.update(dt)}
if(idleAction&&!moving){idleMixer?.update(dt);vrmRig?.update(dt)}const desired=new THREE.Vector3();const lookTarget=new THREE.Vector3();const intro=!activeRef.current;if(intro){const push=(Math.sin(t*.22)+1)*.5,sweep=Math.sin(t*.18)*.82;desired.set(sweep,2.5,9.25-push*.75);lookTarget.set(0,1.18,4.15)}else if(viewMode===0){desired.set(player.x+Math.sin(orbit)*distance,3.05,player.z+Math.cos(orbit)*distance);lookTarget.set(player.x,1,player.z)}else if(viewMode===1){desired.set(player.x+Math.sin(orbit)*3.2,2.35,player.z+Math.cos(orbit)*3.2);lookTarget.set(player.x,1.1,player.z)}else{const forward=new THREE.Vector3(-Math.sin(orbit),0,-Math.cos(orbit));desired.copy(player).addScaledVector(forward,.14);desired.y=1.55;lookTarget.copy(desired).addScaledVector(forward,8)}if(!intro&&viewMode!==2){desired.x=THREE.MathUtils.clamp(desired.x,-9.25,9.25);desired.z=THREE.MathUtils.clamp(desired.z,-9.25,9.25);desired.y=Math.min(desired.y,6.9)}if(avatar)avatar.visible=intro||viewMode!==2;camera.position.lerp(desired,intro?.035:.09);camera.lookAt(lookTarget);let near:string|null=null;if(!intro){for(const d of doors)if(player.distanceTo(d.p)<2.4)near=d.id;if(player.distanceTo(new THREE.Vector3(0,0,2.7))<1.7&&keys.has("e"))onMap()}if(near!==lastNear){lastNear=near;onNearby(near)}renderer.render(scene,camera)};
loop();return()=>{cancelAnimationFrame(raf);disposeDining();ro.disconnect();window.removeEventListener("keydown",down);window.removeEventListener("keyup",up);renderer.domElement.removeEventListener("pointerdown",pointerDown);renderer.domElement.removeEventListener("pointermove",pointerMove);renderer.domElement.removeEventListener("pointerup",pointerUp);renderer.domElement.removeEventListener("wheel",wheel);renderer.dispose();host.removeChild(renderer.domElement)}} ,[]);return <div className="game-canvas" ref={mount}/>}
